# Generated by Django 5.2.5 on 2025-08-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="id_document_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("FRONTDESK", "Front Desk"),
                    ("HOUSEKEEPING", "Housekeeping"),
                    ("MANAGER", "Manager"),
                ],
                default="FRONTDESK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
