# Repository Settings
repository:
  # Pull Requests settings
  allow_merge_commit: true
  allow_squash_merge: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true
  
# Branch Protection Rules
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true  # Require branches to be up to date before merging
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: false  # Don't enforce on admin users
      restrictions: null  # No restrictions on who can push
