# Generated by Django 5.1.5 on 2025-08-31 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.AutoField(primary_key=True, serialize=False)),
                ("room_number", models.CharField(max_length=10, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("Suite", "Suite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Double", "Double"),
                            ("King", "King"),
                            ("Queen", "Queen"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Occupied", "Occupied"),
                            ("Maintenance", "Maintenance"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
